### PR TITLE
Towards DPDK 20.02

### PR DESCRIPTION
**Pull request by gkatsikas**
Compliance with DPDK 20.02-rc1

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
Great! I actually needed it exactly right now :p

**Comment by gkatsikas** [comment]
Good timing :D
Let's keep the PR alive until the final 20.02.

**Comment by gkatsikas** [comment]
dpdk.md is getting very complex, we should do something about it

**Comment by tbarbette** [comment]
I already added the compatibility with the new meson build system of DPDK (and linking with libdpdk as OSes do). The Make system will be removed at some point and at that point we'll stop changing that file.

**Pull request merged**
