### PR TITLE
rx vlan offload

### PR DESCRIPTION
**Pull request by reuvenperetz**

### CODE REVIEW

**Comment by tbarbette** [comment]
The code seems good! Could you just change the commit text to reflect what are the changes, what they allow, why they are needed? git commit --amend

**Comment by reuvenperetz** [comment]
Thanks! Regards "why they are needed?", maybe it would be better to edit the element's wiki page?
I didn't want the message to be way to long...

**Comment by tbarbette** [comment]
The commit message is fine for the title. You can then add an empty line and more description, that will only appear when someone wants the detail of the commit.

**Comment by reuvenperetz** [comment]
Sorry, left too much garbage... Should I close this one and create a new one?

**Comment by tbarbette** [comment]
Typically you can keep the the PR, rebase on origin/master with "git rebase origin/master" and then force-push to the PR (git push ... --force). That will clean things up, indeed you have multiple merge commits here.

**Comment by reuvenperetz** [comment]
Yes, thank you, I'll keep that in mind for next time. It's just that I wasn't sure, and it got too messy... :/

**Pull request closed without merging**
