### PR TITLE
LRO, Rx jumbo frames, and VLAN extend offloading

### PR DESCRIPTION
**Pull request by gkatsikas**
To allow Rx jumbo frames offloading it is necessary
to set max_rx_pkt_len, which was not set by FastClick.
Also, fixed the initial VLAN filter and strip configuration
status (which was mistakenly set to true).
Messages are added to notify users about the status of
the offloading features when turned on.

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by gkatsikas** [comment]
I will fix compatibility issues asap

**Comment by tbarbette** [comment]
Seems good after rebasing. I also fixed all spaces in queuedevice.cc

**Comment by tbarbette** [comment]
I forced-push a rebase to verify it's compiling now

**Comment by gkatsikas** [comment]
Hopefully my last patch will solve the issue with 17.08

**Comment by gkatsikas** [comment]
> No it is not. This offloading feature has been around since the time DPDK was still under the Intel umbrella.
> I didn't know what was the first version supported by FastClick (probably 2.2 or 2.0), so I put it this way

Finally, it makes no sense to keep such an old compatibility with DPDK 1.7.0, because to set this offload you need to access different data structures which changed several times until 19.08.
In order to keep the code readable, I simply demand DPDk 17.11 or higher for this feature (as happens with most offloading features present in this library).

**Comment by gkatsikas** [comment]
I rebased the commits into one to allow easier merge

**Comment by tbarbette** [comment]
Oh yeah, sorry. I forgot this one. Thanks !

**Pull request merged**
