### PR TITLE
SetipDscp

### PR DESCRIPTION
**Pull request by gkatsikas**

### CODE REVIEW

**Comment by tbarbette** [comment]
simple_action_batch should not be implemented if you have both pull_batch and push_batch (which is the best case as simple_action(_batch) add a virtual call).

ALso the pull_batch seems wrong, it pulls a batch and return it untouched.

**Comment by gkatsikas** [comment]
I will remove the simple_action_batch, but why pull_batch is wrong? The batch pointer is filled by the pull() for every packet. This is how other elements implement the pull_batch too.

**Comment by tbarbette** [comment]
It creates a batch by pulling but do nothing with it. smaction(p); should be called for every packet pulled.

**Comment by gkatsikas** [comment]
But smaction is called by pull(), which is called by pull_batch()

**Comment by tbarbette** [comment]
Oh my bad. Okay then.

**Comment by gkatsikas** [comment]
So after my last commit, it is ready to merge :)
Thanks!

**Comment by tbarbette** [comment]
I'm waiting for travis. Yep in my head it was input.pull and not call to the local pull

**Comment by gkatsikas** [comment]
I see that the tests are complaining about elements/tcpudp/fastudpsrcip6.cc:18, which has nothing to do with the modified element.
Why is this the case?

**Comment by tbarbette** [comment]
Master is broken, I'm fixing that

**Pull request merged**
