### PR TITLE
Merge most of PacketMill

### PR DESCRIPTION
**Pull request by tbarbette**
Just not the RAND_ALIGN which was only a paper feature, and not
DPDK_INSIDE that was to simulate VPP model, not entierly finished and is
not the right choice anyway.

### CODE REVIEW

**Comment by aliireza** [comment]
Looks good! 
Do you want me to run some tests before merging? :-p

**Comment by tbarbette** [comment]
If you have time to re-run a packetmill vs fastclick test, it would be great

**Comment by aliireza** [comment]
We are good! 😉

**Comment by tbarbette** [comment]
Great! Thanks for checking :)

**Pull request merged**
