### PR TITLE
Optionally print MAC addresses with IPPrint

### PR DESCRIPTION
**Pull request by gkatsikas**

### CODE REVIEW

**Comment by gkatsikas** [comment]
@tbarbette can you initiate travis?
It looks like I cannot do it myself.

**Comment by tbarbette** [comment]
Something is weird. I can't either.

**Comment by tbarbette** [comment]
Did you test "make check" ? The IPPrint change may cause tests to fail. Better to wait for travis...

**Comment by tbarbette** [comment]
Though as the default is to not change anything it should not be problematic...

**Comment by gkatsikas** [comment]
> Did you test "make check" ? The IPPrint change may cause tests to fail. Better to wait for travis... Else I can set up a gitlab-ci at KTH.

Yes, I tried make check, everything looks good with respect to IPPrint tests

**Comment by gkatsikas** [comment]
If travis revoked your account, then it is a good idea to setup CI/CD at KTH

**Pull request merged**
