### PR TITLE
Major Metron upgrade

### PR DESCRIPTION
**Pull request by gkatsikas**
This upgrade follows a pull request to ONOS for the
control plane part of Metron, including:
 * Refactored REST API with consistent resource names
 * Extended REST API with more management operations
    * Time exchange between Metron server and ONOS
    * Controller-driven NIC port configuration
    * NIC table statistics' report to ONOS
    * NIC queue descriptions' report to ONOS
    * Server connect/disconnect operations driven by ONOS
    * Additional system statisticss (CPU caches and memory)
 * Click's string library extended
 * Fixed deprecated naming conventions (e.g., Flow Director)
 * Metron example configurations updated
 * Metron documentation updated

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by gkatsikas** [comment]
@tbarbette I know it is very hard to review this patch as it contains a whole lot of new things, but comments at a quick glance are welcome.

**Comment by tbarbette** [comment]
Could you try to split the commit, at least for the easy parts like String? It would be better when searching in history and to review :)

**Comment by gkatsikas** [comment]
Testies are burning indeed, but they have lower priority at the moment. Let's keep this pull request open until the control plane part gets approved by ONOS.

**Comment by gkatsikas** [comment]
ONOS just approved my updates and the patch is part of several ONOS branches (master, onos-2.3, onos-2.2), while integration with onos-1.15 is underway.
We can proceed with merging the data plane part now

**Comment by gkatsikas** [comment]
The control-plane part of this patch is now part of all LTS ONOS releases (1.15, 2.2, 2.3) and master. I believe it is time to merge and then refactor the FlowRuleManager..

**Pull request merged**
