### PR TITLE
IPPair unnecessarily re-defined in LinkTable

### PR DESCRIPTION
**Pull request by gkatsikas**
Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
And it does not need any include on top of it?

**Comment by gkatsikas** [comment]
Apparently no extra includes are needed :)
Let's merge

**Comment by tbarbette** [comment]
And you compiled with wifi enabled ?  Because redefinition prevents compilation so it would not have worked before.

Le 11 oct. 2019 23:01, Georgios Katsikas <notifications@github.com> a écrit :

Apparently no extra includes are needed :)
Let's merge

-

**Comment by gkatsikas** [comment]
Yes, initially I compiled with wifi enabled and got the redefinition error.
After the commit, it works fine.
If you disable wifi, linktable is not compiled at all, so no errors either.

**Comment by tbarbette** [comment]
Okay then !  Thanks !

**Pull request merged**
