### PR TITLE
integrating LLVM passes to packetmill.cc

### PR DESCRIPTION
**Pull request by aliireza**
@tbarbette Can you check this?

I still need to add some checks, but this is the basic version. I could still do the click-llvm-opt or separate some parts if you think it is necessary.

### CODE REVIEW

**Comment by tbarbette** [comment]
Can you move the functions that do the reordering etc in something like lib/ or tools/lib ? So we keep packetmill.cc just as a "main".
This morning I had plan to fix the CI issues also... :p

**Comment by aliireza** [comment]
Yes! I wasn't sure where to put it :-p 

Nice!

**Comment by aliireza** [comment]
@tbarbette Can you check now? :-p 

Should we wait for the tests before merging?

**Comment by tbarbette** [comment]
Can you rebase now I fixed the CI? :p

**Comment by aliireza** [comment]
Passed :-p

**Pull request merged**
