### PR TITLE
Prevent potential access to unallocated memory in queue dev

### PR DESCRIPTION
**Pull request by gkatsikas**
This might occur when another element has been configured prior
to a queue device and attempts to call the thread_for_queue
function

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
I would actually prefer this to be an assert() and set the dependency right, eg set the initialization of the caller after FromDPDKDevice. Here we would miss important bug. Also this function is called a lot in the fast path. It would be  better to do the check in get_spawning_threads. Other uses of _thread... are sure to be after initialization. What Element was the caller in your case?

**Comment by gkatsikas** [comment]
In my test, the problem is likely caused by TimestampDiff during configure().
Specifically, in this function TimestampDiff calls get_passing_threads() which invokes thread_for_queue() in queuedevice before initialize_tasks() is called (to allocate the _queue_to_thread memory).

If I just replace my commit with an assert, is it ok for now?

**Comment by gkatsikas** [comment]
This patch fixes the issue between FromDPDKDevice and TimestampDiff.
If other elements try to access thread information before being initialized (e.g., at the configuration phase), then the assertion will be fired.

**Comment by tbarbette** [comment]
Still it will add multiple check for each packet in the fast path. I would prefer the check being done outsite of thread_for_queue, in get_spawning_threads for example. Thread_for_queue is sure to be inialized after all elements initialization, so no need to check that in the fast path.

**Comment by gkatsikas** [comment]
Any additional insights on this?

**Comment by tbarbette** [comment]
Thanks. And you solve the bug then...

**Comment by gkatsikas** [comment]
Can you also merge all the latest changes with Metron?

**Comment by tbarbette** [comment]
Done

**Comment by gkatsikas** [comment]
Super!

**Pull request merged**
