### PR TITLE
Merge Fastclick in Metron

### PR DESCRIPTION
**Pull request by tbarbette**
Might be done a little bit quickly. To be checked again. The deactivation of enable-flow-api might not work (I wanted that for RSS++ too).

### CODE REVIEW

**Comment by gkatsikas** [comment]
I believe we can merge at this point.

**Comment by tbarbette** [comment]
Actually RSS++ merge was a mistake on my end, that part is not in so the flag does not make sense yet...

**Comment by tbarbette** [comment]
I cleaned the history mentioning your change in the merge commit and merged the last fix, I had skipped one of your comments it seems.

**Comment by gkatsikas** [comment]
Looks good to me!

**Pull request merged**
