### PR TITLE
Support for DPDK 20.08

### PR DESCRIPTION
**Pull request by gkatsikas**
* v20.08-rc1
* v20.08-rc2
* v20.08-rc3
* v20.08-rc4

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
Good for the final RC ? 
Thanks!

**Comment by gkatsikas** [comment]
> Good for the final RC ?
> Thanks!

Yes, it is ready to rebase and merge

**Comment by gkatsikas** [comment]
> > Good for the final RC ?
> > Thanks!
> 
> Yes, it is ready to rebase and merge

Ping :p

**Comment by tbarbette** [comment]
Pong! Thanks ! :p

**Pull request merged**
