### PR TITLE
String split returns empty vector when no input

### PR DESCRIPTION
**Pull request by gkatsikas**
Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by bcronje** [comment]
Could you maybe update String::split documentation as well, as it currently has find_left documentation?

**Comment by tbarbette** [comment]
Thanks :p I was probably not into documentation when I pushed that ^^

**Comment by tbarbette** [comment]
Oh but wait, if I just asks to split "hello" with the "," vector, what will I get?
The normal behavior of split in other languages is to pass a vector with only "hello". You did not change that right?

**Comment by gkatsikas** [comment]
No the patch does not work like that :p
In this case it will return an empty vector.

The problem is when the input string is empty.
In this case the old code returns a vector with 1 element, which is the empty string.
Ideally, we want it to return an empty vector, don't we?

I could modify the patch to return an empty vector if the string is empty before the loop starts. Then the rest of the method will be the same as before this patch.

**Pull request merged**
