### PR TITLE
Preliminary support for DPDK 18.08

### PR DESCRIPTION
**Pull request by gkatsikas**
This patch is based on DPDK 18.08-rc1

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by gkatsikas** [comment]
Do not merge yet. Let this pull request be alive through the whole 18.08 life-cycle

**Comment by gkatsikas** [comment]
While compilation works, I see a run-time issue with 18.08-rc2 and Intel 82599 NICs.
When I start a test app, I get:

Initializing DPDK
Ethdev port_id=0 invalid rss_hf: 0x3afbc, valid value: 0x38d34
master.click:117: While initializing ‘io0/td :: ToDPDKDevice’:
  Cannot initialize DPDK port 0 with 8 RX and 8 TX queues
  Error 1 : Operation not permitted
Router could not be initialized!

Mellanox MLX5 works fine :)

**Comment by tbarbette** [comment]
I would bet the old igb_uio from DPDK 18.05 was loaded and this would be your problem. Monday thoughts.

**Comment by gkatsikas** [comment]
Could be the case, I will check again..

**Comment by gkatsikas** [comment]
18.08-rc3 does not introduce additional dependencies and does not require any fixes compared to 18.0-rc2. However, I still get the same error when using Intel NICs. I am pretty sure I load the new (correct driver. There is something else wrong here.. Mellanox still works fine!

**Comment by tbarbette** [comment]
As a reminder, use this as default : 
"preferred Rx/Tx parameters.

Rather than applications providing explicit Rx and Tx parameters such as queue and burst sizes, they can request that the EAL instead uses preferred values provided by the PMD, falling back to defaults within the EAL if the PMD does not provide any. The provision of such tuned values now includes the ixgbe PMD."

**Comment by tbarbette** [comment]
I pushed to master directly without really wanting it. I fixed it, see the commit for more details. The problem was the default RSS parameters that are now verified for unsupported mode.

**Comment by gkatsikas** [comment]
No problem at all. I will do my tests tomorrow, including Metron. Hope it works just fine

**Comment by gkatsikas** [comment]
FastClick master with DPDK 18.08 works for me!
It is time to merge the changes with metron as 18.08 brings several enhancements on the Flow API.

**Pull request closed without merging**
