### PR TITLE
TokenBucket: use 64bit if supported

### PR DESCRIPTION
**Pull request by tbarbette**
Allows all elements such as ratedsource, ratedsplitter, ratedunqueue,
and bandwidthratedunqueue to use > 4G rate.

tokenbucket64 could have lass copy pasting from tokenbucket, but I don't have time for this... I also changed the way it works a little. 32bit token buckets use overflow value as MAX. The 32bit value must therfore be scaled.
While with 64bit, I prefer to keep a reference to the max, and have easier and faster calculation.

### CODE REVIEW

**Comment by tbarbette** [comment]
It seems travis does not understand uint64_t... To be continued.

**Comment by pallas** [comment]
This should be done with templates and feature checks, right?

**Comment by tbarbette** [comment]
> This should be done with templates and feature checks, right?

Well in the end the 32bit and 64bit version do not work the same way as we do not need overflow checks and this max value trick. But some factorization could happen, yes... I tried the templating approach first and abandoned...

**Comment by tbarbette** [comment]
Done in #395

**Pull request closed without merging**
