### PR TITLE
Preliminary support for DPDK 19.08

### PR DESCRIPTION
**Pull request by gkatsikas**
This patch supports up to DPDK 19.08-rc2.
More work migth be needed towards 19.08.

Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
I pushed the test for 19.08 but it will not work as the package is not yet available, even for rc ( see http://fast.dpdk.org/rel/ ) should we wait or already merge?

**Comment by gkatsikas** [comment]
I suggest to wait until the very last rc version, as things might change.

**Comment by gkatsikas** [comment]
FastClick compiles against DPDK 19.08-rc4 without any changes.
We are approaching the stable release.

**Comment by gkatsikas** [comment]
19.08 is upstreamed, merge looks safe

**Comment by tbarbette** [comment]
Ok, just re-started the CI, then one of us can merge when it goes through.

**Comment by tbarbette** [comment]
A few fixes due to new merged-in code and change in DPDK target names.
Thanks !

**Pull request merged**
