### PR TITLE
Display message about batching in configure

### PR DESCRIPTION
**Pull request by gkatsikas**
Signed-off-by: Georgios Katsikas <katsikas.gp@gmail.com>

### CODE REVIEW

**Comment by tbarbette** [comment]
It will be overwritten if it's not done in configure.in first. I would suggest doing it in the .in, then do an autoreconf and send both changes.

**Comment by gkatsikas** [comment]
> It will be overwritten if it's not done in configure.in first. I would suggest doing it in the .in, then do an autoreconf and send both changes.

Oh, you are right, I forgot that.
I re-post asap

**Comment by gkatsikas** [comment]
Apparently, configure.in was missing more features than the batching flag.

**Comment by tbarbette** [comment]
Yes I'm not surprised of that... :p Thanks !

**Pull request merged**
