### PR TITLE
Set BURST to 1 by default for bandwidthratedunqueue

### PR DESCRIPTION
**Pull request by tbarbette**
Reading 32 packets will lead to very large imprecision in term of byts

### CODE REVIEW

**Comment by tbarbette** [comment]
@mihaibrodschi  this looks good now. With the fix it's consistent and I think the new values make sense.

**Comment by mihaibrodschi** [comment]
Great! Just one question, from a performance standpoint, isn't setting the burst to 1 the same as (or worse than) disabling batching?

**Comment by tbarbette** [comment]
Yes, but the user can set BURST 32, and anyway one should avoid pull mode. In push mode the problem does not happen.

**Comment by tbarbette** [comment]
I will add a warning.

**Comment by tbarbette** [comment]
Just pushed. If you're up to it you can create something like ExactBandwidthRatedUnqueue which has this internal queue :)

**Pull request merged**
